apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: smb
  name: smb-flexvol-installer
  #namespace: smb-plugin
spec:
  selector:
    matchLabels:
      name: smb
  template:
    metadata:
      labels:
        name: smb
    spec:
      containers:
      - env:
        - name: DNSRESOLVER
          valueFrom:
            configMapKeyRef:
              key: DNSRESOLVER
              name: env-config
        image: plattform.azurecr.io/plattform/smb-flexvol-installer:latest
        imagePullPolicy: Always
        name: smb-flexvol-installer
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /etc/kubernetes/volumeplugins/
            name: volplugins
          - mountPath: /var/log/
            name: varlog
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - operator: Exists
      volumes:
      - hostPath:
          path: /var/log/
        name: varlog
      - hostPath:
          path: /etc/kubernetes/volumeplugins/
          type: DirectoryOrCreate
        name: volplugins
  updateStrategy:
    type: RollingUpdate
