apiVersion: v1
kind: Namespace
metadata:
  name: flex
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: smb-flexvol-installer
  namespace: flex
  labels:
    k8s-app: smb
spec:
  selector:
    matchLabels:
      name: smb
  template:
    metadata:
      labels:
        name: smb
    spec:
      containers:
      - name: smb-flexvol-installer
        image: dtr.nrk.no/mediakvern/smb-flexvol-installer:1.0.1-domain
        imagePullPolicy: Always
        volumeMounts:
        - name: volplugins
          mountPath: /etc/kubernetes/volumeplugins/
        - name: varlog
          mountPath: /var/log/
      tolerations:
      - operator: "Exists"
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/
      - name: volplugins
        hostPath:
          path: /etc/kubernetes/volumeplugins/
          type: DirectoryOrCreate
      nodeSelector:
        beta.kubernetes.io/os: linux
